palette = "matugen"

[palettes.matugen]
black = "{{colors.surface_container.default.hex}}"
red = "{{colors.error.default.hex}}"
green = "{{colors.primary.default.hex}}"
yellow = "{{colors.tertiary.default.hex}}"
blue = "{{colors.secondary.default.hex}}"
purple = "{{colors.tertiary.default.hex}}"
cyan = "{{colors.secondary.default.hex}}"
white = "{{colors.on_surface.default.hex}}"
orange = "{{colors.tertiary_container.default.hex}}"
gray = "{{colors.surface_variant.default.hex}}"

[character]
success_symbol = "[❯](bold green)"
error_symbol = "[❯](bold red)"

[directory]
style = "blue"

[git_branch]
style = "purple"
symbol = " "

[git_status]
style = "red"

[nodejs]
symbol = " "
style = "green"

[rust]
symbol = " "
style = "orange"

[golang]
symbol = " "
style = "cyan"

[php]
symbol = " "
style = "blue"
